CREATE SEQUENCE reading_document_sequence;

CREATE TABLE READING_DOCUMENT (
    ENTITY_ID   BIGINT PRIMARY KEY DEFAULT nextval('reading_document_sequence'),
    DOCUMENT_ID BIGINT REFERENCES DOCUMENT(ENTITY_ID) ON DELETE CASCADE NOT NULL,
    LANGUAGE_ID BIGINT REFERENCES LANGUAGE(ENTITY_ID) NOT NULL,
    TIME        TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC')
) TABLESPACE ${tbsTables};

CREATE INDEX document_language_idx
    ON READING_DOCUMENT (DOCUMENT_ID, LANGUAGE_ID)
    TABLESPACE ${tbsIdx};

GRANT SELECT, INSERT, UPDATE, DELETE ON READING_DOCUMENT TO ${appRole};
GRANT SELECT ON READING_DOCUMENT TO ${readerRole};